-- =====================================================
-- V4: Create execution_mapping table
-- Purpose: Maps Scheduler triggers to Trial job executions
-- =====================================================

CREATE TABLE execution_mapping (
    id                      BIGSERIAL PRIMARY KEY,
    job_definition_id       BIGINT NOT NULL,
    trigger_id              VARCHAR(100) NOT NULL,
    trial_execution_id      BIGINT,
    spring_batch_execution_id BIGINT,
    status                  VARCHAR(50) NOT NULL DEFAULT 'TRIGGERED',
    triggered_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at              TIMESTAMP,
    completed_at            TIMESTAMP,
    progress_percentage     INTEGER DEFAULT 0,
    progress_message        TEXT,
    error_message           TEXT,
    retry_count             INTEGER DEFAULT 0,
    triggered_by            VARCHAR(100),
    trigger_type            VARCHAR(50) NOT NULL DEFAULT 'SCHEDULED',

    CONSTRAINT fk_execution_job FOREIGN KEY (job_definition_id)
        REFERENCES job_definition(id) ON DELETE CASCADE,
    CONSTRAINT uk_trigger_id UNIQUE (trigger_id),
    CONSTRAINT chk_execution_status CHECK (status IN (
        'TRIGGERED', 'QUEUED', 'STARTING', 'RUNNING',
        'COMPLETED', 'FAILED', 'STOPPED', 'ABANDONED', 'UNKNOWN'
    )),
    CONSTRAINT chk_trigger_type CHECK (trigger_type IN (
        'SCHEDULED', 'MANUAL', 'DEPENDENCY', 'RETRY', 'API'
    )),
    CONSTRAINT chk_progress CHECK (progress_percentage BETWEEN 0 AND 100)
);

-- Indexes for common queries
CREATE INDEX idx_execution_job_id ON execution_mapping(job_definition_id);
CREATE INDEX idx_execution_status ON execution_mapping(status);
CREATE INDEX idx_execution_triggered_at ON execution_mapping(triggered_at DESC);
CREATE INDEX idx_execution_trial_id ON execution_mapping(trial_execution_id) WHERE trial_execution_id IS NOT NULL;
CREATE INDEX idx_execution_running ON execution_mapping(job_definition_id, status)
    WHERE status IN ('TRIGGERED', 'QUEUED', 'STARTING', 'RUNNING');

-- Composite index for dashboard queries
CREATE INDEX idx_execution_dashboard ON execution_mapping(triggered_at DESC, status, job_definition_id);

-- Comments
COMMENT ON TABLE execution_mapping IS 'Maps Scheduler triggers to Trial/Spring Batch job executions';
COMMENT ON COLUMN execution_mapping.trigger_id IS 'Unique ID generated by Scheduler when triggering a job';
COMMENT ON COLUMN execution_mapping.trial_execution_id IS 'Execution ID returned by Trial app';
COMMENT ON COLUMN execution_mapping.spring_batch_execution_id IS 'Spring Batch job execution ID from Trial app';
COMMENT ON COLUMN execution_mapping.trigger_type IS 'SCHEDULED: cron trigger, MANUAL: user triggered, DEPENDENCY: triggered by parent completion, RETRY: automatic retry, API: external API call';
