#!/usr/bin/env node
/**
 * Route Generator for frontend new
 * ==================================
 * Reads uim-graph.json and generates src/routes/allGeneratedRoutes.js
 * with React.lazy() imports for code-splitting.
 *
 * Usage:  node scripts/generate-routes.js
 */

'use strict';
const fs   = require('fs');
const path = require('path');

const ROOT       = path.resolve(__dirname, '..');
const GRAPH_FILE = path.resolve(ROOT, '..', '..', 'CMIPS3.0-main', 'frontend', 'docs', 'uim-graph.json');
const SRC_ROOT   = path.join(ROOT, 'src');
const ROUTES_DIR = path.join(SRC_ROOT, 'routes');

if (!fs.existsSync(GRAPH_FILE)) {
  console.error(`[Error] uim-graph.json not found at: ${GRAPH_FILE}`);
  process.exit(1);
}

fs.mkdirSync(ROUTES_DIR, { recursive: true });

const graph = JSON.parse(fs.readFileSync(GRAPH_FILE, 'utf8'));

// Skip workspace route (handled directly in App.js)
const SKIP_ROUTES = new Set(['/workspace']);

// Collect routes for stub pages that have generated component files
const rows = [];
for (const node of graph.nodes) {
  const { route, component, domain, status } = node;
  if (SKIP_ROUTES.has(route)) continue;
  if (status !== 'stub') continue; // Only include generated stubs; hand-coded pages stay in App.js
  if (!component) continue;

  // Relative import path from routes/ to the component file
  const componentPath = path.join(SRC_ROOT, 'features', domain, 'pages', `${component}`);
  const absRoutesDir = ROUTES_DIR;
  let relImport = path.relative(absRoutesDir, componentPath).replace(/\\/g, '/');
  if (!relImport.startsWith('.')) relImport = './' + relImport;

  rows.push({ route, component, relImport, domain });
}

// Sort by route for consistent output
rows.sort((a, b) => a.route.localeCompare(b.route));

const lines = [
  `// AUTO-GENERATED by scripts/generate-routes.js — DO NOT EDIT MANUALLY`,
  `// ${rows.length} routes covering all UIM-discovered pages`,
  `import React from 'react';`,
  ``,
  `export const allGeneratedRoutes = [`,
];

for (const { route, relImport } of rows) {
  lines.push(
    `  { path: '${route}', Component: React.lazy(() => import('${relImport}')) },`
  );
}

lines.push(`];`);
lines.push(`export default allGeneratedRoutes;`);
lines.push(``);

const outFile = path.join(ROUTES_DIR, 'allGeneratedRoutes.js');
fs.writeFileSync(outFile, lines.join('\n'), 'utf8');
console.log(`[Done] Wrote ${rows.length} routes to src/routes/allGeneratedRoutes.js`);
