/**
 * CMIPS Permission Model - Keycloak Resource-Scope Authorization
 *
 * Uses Keycloak's fine-grained authorization with resources and scopes.
 * Resources represent business modules, scopes represent actions.
 *
 * In Keycloak:
 * - Resources: case-management, timesheet, provider-management, etc.
 * - Scopes: view, create, modify, delete, approve, process, validate, supervise
 * - Policies: Role-based policies mapping roles to access decisions
 * - Permissions: Link resources + scopes + policies
 *
 * The same dashboard is shown to all users - actions are controlled by
 * the user's resource:scope permissions from Keycloak.
 *
 * Core Business Roles Only (51 roles, 15 categories)
 */

// ============================================================
// SCOPES - Actions that can be performed on resources
// ============================================================
export const SCOPES = {
  VIEW: 'view',
  CREATE: 'create',
  MODIFY: 'modify',
  DELETE: 'delete',
  APPROVE: 'approve',
  PROCESS: 'process',
  VALIDATE: 'validate',
  SUPERVISE: 'supervise',
  MANAGE: 'manage',
};

// ============================================================
// RESOURCES - Business modules being protected
// ============================================================
export const RESOURCES = {
  // Case Management
  CASE_MANAGEMENT: 'case-management',
  CASELOAD_ASSIGNMENT: 'caseload-assignment',
  CASE_NOTES: 'case-notes',
  PERSON_NOTES: 'person-notes',

  // Referral & Intake
  REFERRAL_INTAKE: 'referral-intake',

  // Provider
  PROVIDER_MANAGEMENT: 'provider-management',
  PROVIDER_BENEFITS: 'provider-benefits',
  PROVIDER_ENROLLMENT: 'provider-enrollment',

  // Timesheet & Payroll
  TIMESHEET: 'timesheet',
  BVI_NOA_TIMESHEET: 'bvi-noa-timesheet',
  IHSS_PAYROLL: 'ihss-payroll',
  CROSS_COUNTY_PAYROLL: 'cross-county-payroll',
  ADVANCE_PAY_RECON: 'advance-pay-recon',

  // Payment & Financial
  PAYMENT_CORRECTION: 'payment-correction',
  WARRANT: 'warrant',
  WARRANT_REPLACEMENT: 'warrant-replacement',
  COLLECTION: 'collection',
  OVERPAYMENT: 'overpayment',
  DP_PROCESS: 'dp-process',

  // Spectran
  SPECTRAN: 'spectran',

  // Forms & Correspondence
  FORMS_CORRESPONDENCE: 'forms-correspondence',

  // Home Visit & Homemaker
  HOME_VISIT: 'home-visit',
  HOMEMAKER: 'homemaker',

  // State Hearing
  STATE_HEARING: 'state-hearing',

  // Quality Assurance & ICT
  QUALITY_ASSURANCE: 'quality-assurance',
  ICT: 'ict',

  // Help Desk
  HELP_DESK: 'help-desk',

  // County Contractor
  COUNTY_CONTRACTOR: 'county-contractor',

  // Public Authority
  PUBLIC_AUTHORITY: 'public-authority',

  // CDSS
  CDSS: 'cdss',
  CDSS_APPEALS: 'cdss-appeals',
  CDSS_FISCAL: 'cdss-fiscal',
  CDSS_PAYMENT: 'cdss-payment',
  CDSS_PROGRAM_MGMT: 'cdss-program-mgmt',
  CDSS_SSN: 'cdss-ssn',

  // Medi-Cal
  MEDI_CAL_ELIGIBILITY: 'medi-cal-eligibility',

  // Travel Claim
  TRAVEL_CLAIM: 'travel-claim',

  // Security Admin
  SECURITY_ADMIN: 'security-admin',

  // TPF
  TPF_IRS_CERTIFICATION: 'tpf-irs-certification',
  TPF_SICK_LEAVE: 'tpf-sick-leave',

  // WPCS
  WPCS: 'wpcs',

  // Workspace
  WORKSPACE: 'workspace',
};

// ============================================================
// ROLE-RESOURCE-SCOPE MAPPING (51 Core Business Roles)
// Maps each role to the resources and scopes it can access
// ============================================================
export const ROLE_PERMISSIONS = {
  // ===== Case Management (5 roles) =====
  CASEMANAGEMENTROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE, SCOPES.PROCESS],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.DP_PROCESS]: [SCOPES.VIEW, SCOPES.PROCESS],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  CASEMANAGEMENTSUPERVISORROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE, SCOPES.PROCESS, SCOPES.SUPERVISE],
    [RESOURCES.CASELOAD_ASSIGNMENT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.DP_PROCESS]: [SCOPES.VIEW, SCOPES.PROCESS],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.SUPERVISE],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.COUNTY_CONTRACTOR]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  CASEMANAGEMENTWITHAPPROVALROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  CASEMGMTPROVMGMTROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE, SCOPES.PROCESS],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_BENEFITS]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.DP_PROCESS]: [SCOPES.VIEW, SCOPES.PROCESS],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  CASEMGMTWITHAPPROVALPROVMGMTROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_BENEFITS]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  // ===== Case Management + Payroll (8 roles) =====
  CASEMGMTPAYROLLROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE, SCOPES.PROCESS],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.ADVANCE_PAY_RECON]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.WARRANT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.DP_PROCESS]: [SCOPES.VIEW, SCOPES.PROCESS],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  CASEMGMTPAYROLLAPPROVERROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE, SCOPES.PROCESS],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.ADVANCE_PAY_RECON]: [SCOPES.VIEW, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE],
    [RESOURCES.WARRANT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.DP_PROCESS]: [SCOPES.VIEW, SCOPES.PROCESS],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  CASEMGMTPROVMGMTPAYROLLROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE, SCOPES.PROCESS],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_BENEFITS]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.ADVANCE_PAY_RECON]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.WARRANT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.DP_PROCESS]: [SCOPES.VIEW, SCOPES.PROCESS],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  CASEMGMTPROVMGMTPAYROLLAPPROVERROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE, SCOPES.PROCESS],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_BENEFITS]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.ADVANCE_PAY_RECON]: [SCOPES.VIEW, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE],
    [RESOURCES.WARRANT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.DP_PROCESS]: [SCOPES.VIEW, SCOPES.PROCESS],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  CASEMGMTWITHAPPROVALPAYROLLROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.ADVANCE_PAY_RECON]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.WARRANT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  CASEMGMTWITHAPPROVALPAYROLLAPPROVERROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.ADVANCE_PAY_RECON]: [SCOPES.VIEW, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE],
    [RESOURCES.WARRANT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  CASEMGMTWITHAPPROVALPROVMGMTPAYROLLROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_BENEFITS]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.ADVANCE_PAY_RECON]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.WARRANT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  CASEMGMTWITHAPPROVALPROVMGMTPAYROLLAPPROVERROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_BENEFITS]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.ADVANCE_PAY_RECON]: [SCOPES.VIEW, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE],
    [RESOURCES.WARRANT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  // ===== Eligibility & Medi-Cal (4 roles - excluding super roles) =====
  HPMEDSELIGBA1ROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE, SCOPES.PROCESS, SCOPES.SUPERVISE],
    [RESOURCES.CASELOAD_ASSIGNMENT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_BENEFITS]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.DP_PROCESS]: [SCOPES.VIEW, SCOPES.PROCESS],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.SUPERVISE],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.COUNTY_CONTRACTOR]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.MEDI_CAL_ELIGIBILITY]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.CDSS]: [SCOPES.VIEW],
    [RESOURCES.CDSS_APPEALS]: [SCOPES.VIEW, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.CDSS_FISCAL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.CDSS_PAYMENT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.CDSS_PROGRAM_MGMT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.CDSS_SSN]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  HPMEDSELIGBA2ROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.ADVANCE_PAY_RECON]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE],
    [RESOURCES.WARRANT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.MEDI_CAL_ELIGIBILITY]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  HPMEDSELIGBA3ROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW],
    [RESOURCES.COUNTY_CONTRACTOR]: [SCOPES.VIEW],
    [RESOURCES.MEDI_CAL_ELIGIBILITY]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  HPMEDSELIGBA4ROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE, SCOPES.PROCESS],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.DP_PROCESS]: [SCOPES.VIEW, SCOPES.PROCESS],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.MEDI_CAL_ELIGIBILITY]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  // ===== Intake & Referral (1 core role) =====
  REFERRALINTAKEROLE: {
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  // ===== Provider Management (3 roles) =====
  PROVIDERMANAGEMENTROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_BENEFITS]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  PROVIDERMGMTPAYROLLMGMTROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_BENEFITS]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.ADVANCE_PAY_RECON]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.WARRANT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  PROVIDERMGMTPAYROLLAPPROVERROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_BENEFITS]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.ADVANCE_PAY_RECON]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE],
    [RESOURCES.WARRANT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  // ===== Payroll & Financial (6 roles) =====
  PAYROLLROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.ADVANCE_PAY_RECON]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.WARRANT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  PAYROLLMGMTROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.ADVANCE_PAY_RECON]: [SCOPES.VIEW, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE],
    [RESOURCES.WARRANT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  CROSSCOUNTYPAYROLLROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_BENEFITS]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.CROSS_COUNTY_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.ADVANCE_PAY_RECON]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE],
    [RESOURCES.WARRANT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  HPWARRANTREPLACEMENTROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.WARRANT_REPLACEMENT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW],
    [RESOURCES.COUNTY_CONTRACTOR]: [SCOPES.VIEW],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  HPETRAVELCLAIMPAYMENTROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.CDSS]: [SCOPES.VIEW],
    [RESOURCES.CDSS_PAYMENT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.TRAVEL_CLAIM]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  WPCSROLE: {
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE],
    [RESOURCES.WARRANT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.WPCS]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  // ===== Timesheet & Help Desk (4 roles) =====
  TIMESHEETROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  BVINOAANDTIMESHEETMANAGEMENTROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.BVI_NOA_TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  ETIMESHEETHELPDESKROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.BVI_NOA_TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HELP_DESK]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  HDBVINOAANDTSMGMTROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.BVI_NOA_TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HELP_DESK]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  // ===== Public Authority (4 roles) =====
  PUBLICAUTHORITYROLE: {
    [RESOURCES.PUBLIC_AUTHORITY]: [SCOPES.VIEW],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  PABENEFITSROLE: {
    [RESOURCES.PUBLIC_AUTHORITY]: [SCOPES.VIEW],
    [RESOURCES.PROVIDER_BENEFITS]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  PAPROVIDERENROLLROLE: {
    [RESOURCES.PUBLIC_AUTHORITY]: [SCOPES.VIEW],
    [RESOURCES.PROVIDER_ENROLLMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  PAPROVIDERENROLLBENEFITSROLE: {
    [RESOURCES.PUBLIC_AUTHORITY]: [SCOPES.VIEW],
    [RESOURCES.PROVIDER_ENROLLMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_BENEFITS]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  // ===== CDSS (4 roles) =====
  CDSSVIEWROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW],
    [RESOURCES.CDSS]: [SCOPES.VIEW],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  CDSSFISCALROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW],
    [RESOURCES.CDSS]: [SCOPES.VIEW],
    [RESOURCES.CDSS_FISCAL]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  CDSSMODIFYROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.CDSS]: [SCOPES.VIEW],
    [RESOURCES.CDSS_APPEALS]: [SCOPES.VIEW, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.CDSS_PAYMENT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.CDSS_PROGRAM_MGMT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.TPF_IRS_CERTIFICATION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  CDSSPROGRAMMGMTROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE, SCOPES.PROCESS, SCOPES.SUPERVISE],
    [RESOURCES.CASELOAD_ASSIGNMENT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_BENEFITS]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.DP_PROCESS]: [SCOPES.VIEW, SCOPES.PROCESS],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.SUPERVISE],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.COUNTY_CONTRACTOR]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.CDSS]: [SCOPES.VIEW],
    [RESOURCES.CDSS_APPEALS]: [SCOPES.VIEW, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.CDSS_FISCAL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.CDSS_PAYMENT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.CDSS_PROGRAM_MGMT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.CDSS_SSN]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  // ===== Program Management (1 role) =====
  PROGRAMMGMTROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE, SCOPES.PROCESS, SCOPES.SUPERVISE],
    [RESOURCES.CASELOAD_ASSIGNMENT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.PROVIDER_BENEFITS]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.ADVANCE_PAY_RECON]: [SCOPES.VIEW, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.APPROVE],
    [RESOURCES.WARRANT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.DP_PROCESS]: [SCOPES.VIEW, SCOPES.PROCESS],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.APPROVE],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.SUPERVISE],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.QUALITY_ASSURANCE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.ICT]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.COUNTY_CONTRACTOR]: [SCOPES.VIEW, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  // ===== Homemaker (1 role) =====
  HOMEMAKERROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW],
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  // ===== Help Desk (1 role) =====
  HELPDESKROLE: {
    [RESOURCES.HELP_DESK]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  // ===== View/Inquiry (2 roles) =====
  COUNTYVIEWONLYROLE: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW],
    [RESOURCES.REFERRAL_INTAKE]: [SCOPES.VIEW],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.PROVIDER_BENEFITS]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW],
    [RESOURCES.STATE_HEARING]: [SCOPES.VIEW],
    [RESOURCES.COUNTY_CONTRACTOR]: [SCOPES.VIEW],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  HPINQUIRY: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.CASE_NOTES]: [SCOPES.VIEW],
    [RESOURCES.PERSON_NOTES]: [SCOPES.VIEW],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.PAYMENT_CORRECTION]: [SCOPES.VIEW],
    [RESOURCES.WARRANT]: [SCOPES.VIEW],
    [RESOURCES.COLLECTION]: [SCOPES.VIEW],
    [RESOURCES.OVERPAYMENT]: [SCOPES.VIEW],
    [RESOURCES.SPECTRAN]: [SCOPES.VIEW],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW],
    [RESOURCES.HOME_VISIT]: [SCOPES.VIEW],
    [RESOURCES.HOMEMAKER]: [SCOPES.VIEW],
    [RESOURCES.COUNTY_CONTRACTOR]: [SCOPES.VIEW],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  // ===== TPF (1 role) =====
  TPF: {
    [RESOURCES.CASE_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.PROVIDER_MANAGEMENT]: [SCOPES.VIEW],
    [RESOURCES.TIMESHEET]: [SCOPES.VIEW],
    [RESOURCES.FORMS_CORRESPONDENCE]: [SCOPES.VIEW],
    [RESOURCES.TPF_IRS_CERTIFICATION]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.TPF_SICK_LEAVE]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },

  // ===== Admin (1 role) =====
  ADMIN: {
    [RESOURCES.IHSS_PAYROLL]: [SCOPES.VIEW],
    [RESOURCES.SECURITY_ADMIN]: [SCOPES.VIEW, SCOPES.CREATE, SCOPES.MODIFY, SCOPES.DELETE, SCOPES.MANAGE],
    [RESOURCES.WORKSPACE]: [SCOPES.VIEW],
  },
};

// ============================================================
// PERMISSION CHECK FUNCTIONS
// ============================================================

/**
 * Get all resource:scope permissions for a user based on their roles.
 * Combines permissions from all assigned roles.
 *
 * @param {string[]} userRoles - Array of Keycloak role names
 * @returns {Object} Map of resource -> Set of scopes
 */
export function getUserPermissions(userRoles) {
  if (!userRoles || !Array.isArray(userRoles)) {
    return {};
  }

  const permissions = {};

  userRoles.forEach(role => {
    const rolePerms = ROLE_PERMISSIONS[role];
    if (rolePerms) {
      Object.entries(rolePerms).forEach(([resource, scopes]) => {
        if (!permissions[resource]) {
          permissions[resource] = new Set();
        }
        scopes.forEach(scope => permissions[resource].add(scope));
      });
    }
  });

  // Convert Sets to Arrays for easier consumption
  const result = {};
  Object.entries(permissions).forEach(([resource, scopes]) => {
    result[resource] = Array.from(scopes);
  });

  return result;
}

/**
 * Check if user can perform a specific action on a resource.
 *
 * @param {string} resource - Resource name (e.g., 'case-management')
 * @param {string} scope - Scope/action name (e.g., 'view', 'modify')
 * @param {string[]} userRoles - Array of Keycloak role names
 * @returns {boolean} True if allowed
 */
export function canAccess(resource, scope, userRoles) {
  if (!resource || !scope || !userRoles) return false;

  const permissions = getUserPermissions(userRoles);
  const resourcePerms = permissions[resource];
  if (!resourcePerms) return false;

  return resourcePerms.includes(scope);
}

/**
 * Check if user can view a resource.
 * @param {string} resource - Resource name
 * @param {string[]} userRoles - Array of Keycloak role names
 * @returns {boolean}
 */
export function canView(resource, userRoles) {
  return canAccess(resource, SCOPES.VIEW, userRoles);
}

/**
 * Check if user can create on a resource.
 * @param {string} resource - Resource name
 * @param {string[]} userRoles - Array of Keycloak role names
 * @returns {boolean}
 */
export function canCreate(resource, userRoles) {
  return canAccess(resource, SCOPES.CREATE, userRoles);
}

/**
 * Check if user can modify a resource.
 * @param {string} resource - Resource name
 * @param {string[]} userRoles - Array of Keycloak role names
 * @returns {boolean}
 */
export function canModify(resource, userRoles) {
  return canAccess(resource, SCOPES.MODIFY, userRoles);
}

/**
 * Check if user can delete on a resource.
 * @param {string} resource - Resource name
 * @param {string[]} userRoles - Array of Keycloak role names
 * @returns {boolean}
 */
export function canDelete(resource, userRoles) {
  return canAccess(resource, SCOPES.DELETE, userRoles);
}

/**
 * Check if user can approve on a resource.
 * @param {string} resource - Resource name
 * @param {string[]} userRoles - Array of Keycloak role names
 * @returns {boolean}
 */
export function canApprove(resource, userRoles) {
  return canAccess(resource, SCOPES.APPROVE, userRoles);
}

/**
 * Check if user has a specific Keycloak role.
 * @param {string} role - Role name to check
 * @param {string[]} userRoles - Array of Keycloak role names
 * @returns {boolean}
 */
export function hasRole(role, userRoles) {
  if (!role || !userRoles) return false;
  return userRoles.includes(role);
}

/**
 * Get all resources a user has access to (with any scope).
 * @param {string[]} userRoles - Array of Keycloak role names
 * @returns {string[]} Array of resource names
 */
export function getAccessibleResources(userRoles) {
  return Object.keys(getUserPermissions(userRoles));
}

/**
 * Check if user has any access to a resource (any scope).
 * @param {string} resource - Resource name
 * @param {string[]} userRoles - Array of Keycloak role names
 * @returns {boolean}
 */
export function hasAnyAccess(resource, userRoles) {
  const permissions = getUserPermissions(userRoles);
  return !!permissions[resource] && permissions[resource].length > 0;
}

export default {
  SCOPES,
  RESOURCES,
  ROLE_PERMISSIONS,
  getUserPermissions,
  canAccess,
  canView,
  canCreate,
  canModify,
  canDelete,
  canApprove,
  hasRole,
  getAccessibleResources,
  hasAnyAccess,
};
